### ISSUE TITLE
Sample config file

### ISSUE THREAD

**Issue by zchef2k** [Dup4/ssh-uptime#1]
I like the simple approach to uptime monitoring. Can you share a sample config file, I thought I could figure it out based on config.py but I'm missing something.

Thank you.

**Comment by Dup4** [comment]
I have added a sample configuration. #2 

But I would recommend you to use https://github.com/megaease/easeprobe

**Comment by zchef2k** [comment]
Thank you for affirming the sample config. I will certainly check out the other project. 👍🏻
